// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwjpbxplhkdvwyvyostn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3anBieHBsaGtkdnd5dnlvc3RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5Mzg0OTMsImV4cCI6MjA2MDUxNDQ5M30.LtoVm-cMXcfxKRN8Myzje6Z1wHh_iO0Xemcye3-dK0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);